# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Files/Vivado/EE/EE-GITHUB/Extended-Essay/Extended-Essay-master/Extended-Essay-master/Single_location test/Single_location test.cache/wt} [current_project]
set_property parent.project_path {D:/Files/Vivado/EE/EE-GITHUB/Extended-Essay/Extended-Essay-master/Extended-Essay-master/Single_location test/Single_location test.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {{D:/Files/Vivado/EE/EE-GITHUB/Extended-Essay/Extended-Essay-master/Extended-Essay-master/Single_location test/Single_location test.srcs/sources_1/new/compare_test.v}}
read_xdc {{D:/Files/Vivado/EE/EE-GITHUB/Extended-Essay/Extended-Essay-master/Extended-Essay-master/Single_location test/Single_location test.srcs/constrs_1/imports/basys3_master/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/Files/Vivado/EE/EE-GITHUB/Extended-Essay/Extended-Essay-master/Extended-Essay-master/Single_location test/Single_location test.srcs/constrs_1/imports/basys3_master/Basys3_Master.xdc}}]

synth_design -top compare_test -part xc7a35tcpg236-1
write_checkpoint -noxdef compare_test.dcp
catch { report_utilization -file compare_test_utilization_synth.rpt -pb compare_test_utilization_synth.pb }
